name: akos.ma workflow
on:
  schedule:
    # https://crontab.guru/#30_7_*_*_5
    - cron: '30 7 * * 5'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest akos.ma blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "AKOSMA"
          commit_message: "Updated readme with the latest akos.ma articles"
          feed_list: "https://akos.ma/index.xml"
          max_post_count: 4
